// Mocks generated by Mockito 5.4.4 from annotations
// in blott_news/test/features/news_dashboard/data/repositories/news_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blott_news/core/data/network/dio_client.dart.dart' as _i2;
import 'package:blott_news/features/news_dashboard/data/sources/news_api_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDioClient_0 extends _i1.SmartFake implements _i2.DioClient {
  _FakeDioClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NewsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsApiService extends _i1.Mock implements _i3.NewsApiService {
  MockNewsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DioClient get dioClient => (super.noSuchMethod(
        Invocation.getter(#dioClient),
        returnValue: _FakeDioClient_0(
          this,
          Invocation.getter(#dioClient),
        ),
      ) as _i2.DioClient);

  @override
  _i4.Future<List<dynamic>> fetchNews({
    required String? category,
    required String? token,
    required int? minId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNews,
          [],
          {
            #category: category,
            #token: token,
            #minId: minId,
          },
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);
}
